# Generated by Django 3.2.11 on 2022-07-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20220709_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='movie_name'),
        ),
    ]
