# Generated by Django 3.2.11 on 2022-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Kventin Tarantino', max_length=100),
        ),
    ]
