# Generated by Django 3.2.11 on 2022-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(default='sugar_daddy@gmail.com', max_length=254),
        ),
    ]
